### PR TITLE
Malay (ms) translation

### PR DESCRIPTION
**Pull request by Thaza-Kun**
Initiated a malay (ms) translation:
- Added `ms.termbase.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
@Thaza-Kun Any update on this? Do you prefer to close it and re-open it when you have time? Thanks!

**Comment by Thaza-Kun** [comment]
Sorry for the slow progress. I think it is better to do as you say: to close it now and reopen it later.

**Comment by Thaza-Kun** [comment]
Pinging @MagusWyvern for confirmation

**Comment by MagusWyvern** [comment]
Reviewed the translation, looks good to me! Thanks Thaza-Kun for helping with most of the translations! :D

**Comment by Thaza-Kun** [comment]
Thank you @MagusWyvern for the review.

@ericaxu this translation is ready. Sorry for the delay.

**Comment by ericaxu** [comment]
Sorry for the delay on my end! Thank you for your amazing work.

**Pull request merged**
