### PR TITLE
Clarified Default New Mode Option

### PR DESCRIPTION
**Pull request by whitenoisedev**
I have got a couple of questions and bug reports about this.
Some people expect this setting to apply to notes opened in the same pane, whereas this setting is only about new panes.

### CODE REVIEW

**Comment by ericaxu** [comment]
I think we might should have changed the behavior instead. When we added the feature, I think we imagined it to enforce it on each navigation rather than just opening new panes.

**Comment by ericaxu** [comment]
@lishid What do you think? We should enforce default open mode when go to another file _in the same pane_, or is that hard to do?

**Comment by lishid** [comment]
Enforcing default mode in the same pane basically means there won't be a way to "keep the current view mode" right? It'll force to preview or edit always whenever you navigate.

**Comment by ericaxu** [comment]
Yeah, I think that's correct. @WhiteNoise-Dev: That's what people were confused about, right?

**Comment by WhiteNoise-Dev** [comment]
@ericaxu yes, that's what they were expecting. However, we didn't get a lot of complaints/confusion about this (just 2). I think what we are doing currently is okay, we just need to clarify the setting (hence the PR). Eventually, all of this will be eased with wyswyg.

**Comment by whitenoisedev** [comment]
I've got another confused user today. Whatever we are doing now is fine for most users except a few who expect the toggle to apply to all panes (not just new panes). So I suggest just merge this PR and make it clear what that toggle does.

**Comment by ericaxu** [comment]
> I've got another confused user today. Whatever we are doing now is fine for most users except a few who expect the toggle to apply to all panes (not just new panes). So I suggest just merge this PR and make it clear what that toggle does.

Thanks, got it. After some discussion I think we'll keep current behavior and merge this doc change.

**Pull request merged**
