### PR TITLE
Completed Turkish(tr) translation

### PR DESCRIPTION
**Pull request by LupusCaelum**
🎊 v0.13.23 strings added and translated.
🎇The translation is complete, including incomplete texts, so that it is natural and the whole is meaningful.

### CODE REVIEW

**Comment by ericaxu** [comment]
Sorry I didn't respond sooner!

Could you please see if you can figure out how to handle the merge conflicts? You might need to work with the author of #601 to resolve them as you both touched the same file.

**Comment by LupusCaelum** [comment]
Not problem;
I think, i solved the conflicts now. Can you re-check please?

**Review by LupusCaelum — COMMENTED** [review]
updated...

**Comment by ericaxu** [comment]
Thank you for your amazing work!

**Pull request merged**
