### PR TITLE
lsilva.m_translations01

### PR DESCRIPTION
**Pull request by lsilvam**
here goes my first contribution

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi @lsilvam , Thank you for your work!

There are some merge conflicts presumably with pull requests that I merged earlier, do you think you have everything you need to resolve them?

**Comment by lsilvam** [comment]
Hi @ericaxu -- I decided to keep my translation, since the one raising the conflict did not have all the fields translated; hope its ok.
Also, it might be a good idea to create a new language: pt-br ([as already discuss in Discord](https://discordapp.com/channels/686053708261228577/741594204769222719/743214156781715546)).

**Comment by ericaxu** [comment]
@lsilvam Definitely!

Re: pt-BR, you may want to chime in here: #60

**Comment by ericaxu** [comment]
I'm so sorry that I created some merge conflicts, it seems like. I mistakenly thought this PR were in an unmergeable state and merged #65 before this one. We normally merge the earliest first.

So sorry!

**Comment by lsilvam** [comment]
@ericaxu no problem. I see now that the portuguese translation is complete.

**Comment by ericaxu** [comment]
Thank you for understanding, @lsilvam ! I'll close this for now. Let me know anytime if I should re-open it.

**Pull request closed without merging**
