### PR TITLE
de: update mainly wording in UI Mobile and UI Plugins

### PR DESCRIPTION
**Pull request by 42sol-eu**
There where many mixed or complex construction, most of them in the mobile toolbar.

I tried to make them easier to understand and shorter.

Please feel free to discuss my choices.

### CODE REVIEW

**Comment by marcjulianschwarz** [comment]
I had a look at your changes and found several typos and inconsistencies, which I will list here. The other changes you made were good and removed lots of anglicisms and complex structures which weren't necessary.

Line *207*: `keinen Benutzerkonto` should be `kein Benutzerkonto`

Line *222-230*: Some inconsistencies with `aktiviert` vs `eingeschaltet` and `deaktiviert` vs `ausgeschaltet`, you are using both versions here. In my opinion `aktiviert` and `deaktiviert` make more sense since you activate plugins rather than turning them on and off (like a machine).

Line *240*: `des Erweiterungsdefinition` should be `der Erweiterungsdefinition`
Line *267*: `Erwieterungen` should be `Erweiterungen`

Line *270-273*: I don't think the changes make this easier to understand. Especially the original "Downloads" part is better in my opinion.

Line *296-297*: I think it is unclear what `Ebene höher` and `Ebene tiefer` should mean in this context. It should somehow include the word `List` (list) to make this more clear.

(Line *311-312*): I don't know why you removed "global" here, does it have no meaning in that context? 

That's it. I think it would be a good idea if someone else would look over this too since it introduced a lot of changes which might conflict with other areas of Obsidian.

**Comment by 42sol-eu** [comment]
Thanks Marc, 
I am completely with you. As I wrote. This was more or less a test how the process works. 

I am mainly working with the English version  of Obsidian anyway. 

My first goal is to update the German help vault. But I was stumbling over some very strange UI translations in German. 

I will use your input to fix the items. I also have started a glossary as many other translators did to solve the bigger picture issues. 

I also discussed it with a translator and spotted some mistakes I made.

**Comment by marcjulianschwarz** [comment]
No problem, do you mind sharing the glossary?

If there is more help needed to translate or to have a second opinion on some formulations, I am always ready to see how I could help.

**Comment by 42sol-eu** [comment]
Yes of course. Sharing was the plan, I only was waiting for some kind of reaction on this pull request. I plan to do it this weekend.

**Comment by 42sol-eu** [comment]
- [x] Line 207: keinen Benutzerkonto should be kein Benutzerkonto

>> fixed article

- [x] Line 222-230: Some inconsistencies with aktiviert vs eingeschaltet and deaktiviert vs ausgeschaltet, you are using both versions here. In my opinion aktiviert and deaktiviert make more sense since you activate plugins rather than turning them on and off (like a machine).

>> used eingeschaltet and ausgeschaltet, becaus that is how switching on and off is most commonly used in German.

- [x] Line 240: des Erweiterungsdefinition should be der Erweiterungsdefinition

>> fixed article

- [x] Line 267: Erwieterungen should be Erweiterungen

>> fixed typo

- [c] Line 270-273: I don't think the changes make this easier to understand. Especially the original "Downloads" part is better in my opinion.

>> removed my changes


- [x] Line 296-297: I think it is unclear what Ebene höher and Ebene tiefer should mean in this context. It should somehow include the word Liste (list) to make this more clear.

>> added "Listenelement eine" .. this makes it very long but keep this as a first better solution and discuss it with more peoble

- [c] (Line 311-312): I don't know why you removed "global" here, does it have no meaning in that context?

>> needs further discussen removed it from that pull request.
>> It does not in my opinion. The core problem is that `global` does not easily translate into German. The usage of the German `global` means `worldwide`. I think  

That's it. I think it would be a good idea if someone else would look over this too since it introduced a lot of changes which might conflict with other areas of Obsidian.

>> Thats up to the Obsidian team. In my opinion the German is still in a very rough state and should be moved forward quickly. But I do not know if thats the teams approach.

**Comment by FloriF** [comment]
I think your changes are great and this could be merged.

(As for the 'aktivieren/einschalten' discussion: Personally, I'd vote for using activate, for the same reason as @marcjulianschwarz - however, this should be further discussed once a glossary exists and other wording problems are revisited - not in this pull request.)

**Comment by 42sol-eu** [comment]
You asked for it...
I thought why not use Obsidian to translate Obsidian - and discuss about it 

https://github.com/42sol-eu/obsidian_translation_shared

**Pull request closed without merging**
