### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by alltagsverstand**
Some minor fixes.
Translated quick-switcher plugin

### CODE REVIEW

**Comment by auxilium-systems** [comment]
Looks good. What do you think about the term "Schnellauswahl" instead of "Notizauswahl-Dialog"? - it sounds a bit clunky to me.

**Comment by alltagsverstand** [comment]
@auxilium-systems  yes, that was actually the term I was struggling with - in German, any noun for "quick switcher" sounds much more cumbersome...
I also thought about "Schnellzugriff" or "Schnellauswahl" - in the end I thought that "Notizauswahl" is more self-explanatory (with a view to _what_ can be switched to....).
Maybe a combination of both could be the smoothest solution? Like "Notizen-Schnellauswahl"

**Comment by ericaxu** [comment]
Thank you for your work! <3

**Comment by auxilium-systems** [comment]
I think we agreed after discussion on discord and alltagsverstand made the changes. So good to go.

**Comment by ericaxu** [comment]
Thank you for your amazing work!

**Pull request merged**
