### PR TITLE
Improved PTBR Translation

### PR DESCRIPTION
**Pull request by ShidoBox**
It's not finished, but it is a step. 😃

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for adding the termbase/glossory!

Re: the issue template, is it for submitting issues about the PTBR translation?

**Comment by ShidoBox** [comment]
Oh, yes. Currently, I'm doing a revamp of the pt-BR translation (discussed on discord) and I wanted to create a more open and dynamic way to fix mistakes. I didn't know this would go to the in the past PR, sorry.

**Comment by ericaxu** [comment]
Hmm it seems something funky is going on with sync, probably caused by some upstream changes... 🤔

**Comment by ShidoBox** [comment]
Yeah, I'm going to delete the fork and create a new one

**Pull request closed without merging**
