### PR TITLE
French : Obsidian 1.0

### PR DESCRIPTION
**Pull request by Lisandra-dev**
Hello.
I updated french string for Obsidian 1.0 !

### CODE REVIEW

**Review by EdualcLaiv — CHANGES_REQUESTED** [review]
Hi,
There is a couple of small things I noticed :

- **Lines 42 and 43** there is a capitalisation inconsistancy. "Mode Édition" with "Mode Lecture" or "Mode édition" with "Mode lecture" would be better than a mix. My guess is for the second option ("Mode édition" with "Mode lecture").

- **Line 781** `"show-debug-info": "Afficher les informations de débogages.",` Why the final dot ? There is none in english here (`"show-debug-info": "Show Debug Info",`).

- **Line 788** `"release-notes": "Notes de mise-à-jour"` => `"release-notes": "Notes de mise-à-jour"` There are no hyphens in the other occurences, and I don't think they're needed. I checked a few dictionnaries and found the locution without hyphens

- **Lines 799 and 800** `"action-collapse-all": "Tout réduire",` and `"action-expand-all": "Développer tout",` is correct but keeping the phrasing consistent would be better ? "Tout réduire" + "Tout développer" would be my favorite formulation, but "Réduire tout" + "Développer tout" works too.
  - Later (lines 1009 & 1010) we have "Tout réduire" + "Tout développer".

- **Line 974** `"menu-opt-backlinks-in-document": "Rétrolien dans le document",` Missing plural : "Rétroliens dans le document".

- **Line 1390** `"option-currently-included-folders": " Ces dossiers sont actuellement inclus:",` => `"option-currently-included-folders": " Ces dossiers sont actuellement inclus :",` There is an insecable space before ":" in french typography (not sure I inserted an actual insecable space here in my comment)

- **Line 1554** `"label-not-sharing": "Ce coffre-fort distant n'est actuellement partagé avec personne..",` Two dots at the end.

- **Line 1557** `"label-leave-vault-confirmation": "Confirmer l'arrêt de la collaboration.",` like earlier, is it normal there is a dot at the end of the sentence in french and not in english ?

And two other remarks, might be useless :

- "vault" is sometimes translated as "coffre" and sometimes as "coffre-fort". Not sure if that's something unwanted or not.
  - (I like "coffre" more, but it could mean both "vault" and "chest" while "coffre-fort" only means "vault")
  
- Sometimes we have "..." (as 3 distincts dots) and sometimes we have "…" (as a unique unicode character).

**Comment by Lisandra-dev** [comment]
Hello! I updated the translation :)

**Comment by Lisandra-dev** [comment]
Hello! I updated the translation with your review :)

**Comment by ericaxu** [comment]
Thank you for your work!

**Pull request merged**
