### PR TITLE
Update ko.json

### PR DESCRIPTION
**Pull request by booerg**

### CODE REVIEW

**Comment by ericaxu** [comment]
Sorry to say there seem to be some conflicts right now. Do you think there's any chance you can resolve them?

**Comment by cherojeong** [comment]
Hello ericaxu, Could you let me know conflicts caused by ko.json or something ? I would like to know when updated ko.json is available to see as officially. because to keep consistence with obsidian-help, I would like to know it. according to updated ko.json, I think I have to update my commits in forked repository of obsidian-help(I already did "pull requests". If this is not caused by ko.json changes. I will refer to someone's changes in ko.json.

**Comment by ericaxu** [comment]
@booerg Can you do a rebase on the master branch please?

**Comment by joethei** [comment]
Closing as this PR has gone stale.
If you are ready continue feel free to reopen it.

**Pull request closed without merging**
