### PR TITLE
Correct and update id.json for 0.9.0

### PR DESCRIPTION
**Pull request by jokysatria**
By using Microsoft Terminology Collection as reference

### CODE REVIEW

**Comment by jokysatria** [comment]
Is there something I can do to resolve this conflict? I already updated my id.json file to the latest version before translating it.

**Comment by jokysatria** [comment]
I just realized that I made some commits (to correct some strings in the editor) before you added some strings for 0.9.0. Is it the cause of the current conflict?

**Comment by ericaxu** [comment]
> Ah, I just realized that I made some commits (to correct some strings in the editor) before you added some strings for 0.9.0. Is it the cause of current conflict?

Possibly, I'll try to resolve the conflicts, sorry about that!

**Comment by ericaxu** [comment]
Thank you so much for your kind words!

**Pull request merged**
