### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by stonkol**
Fixed grammar and spelling error.

Updated some words or lines which wasn't translated.

### CODE REVIEW

**Comment by joethei** [comment]
Please update only one language per pull request.

**Comment by stonkol** [comment]
Ok, I added them separately, but it seems it was pulled together. Did I need to pull one of them again?

**Comment by joethei** [comment]
Yeah

**Comment by stonkol** [comment]
Ok, I will delete the Chinese file and PR in a separate place

**Pull request closed without merging**
