### PR TITLE
ru: Update translation

### PR DESCRIPTION
**Pull request by adem4ik**
- Fixed spelling and punctuation 
- Reworded some translations
- Replaced "E" with "Ё" where it's needed

### CODE REVIEW

**Comment by JxhnnyUt8h** [comment]
- Fixed spelling and punctuation - ok
- Reworded some translations - ok
- Replaced "E" with "Ё" where it's needed - need additional discussion with Ru contributors here: https://t.me/joinchat/FwbKzhpDF5ahXaFJWLfOOg

**Comment by ericaxu** [comment]
Let me know when this is peer reviewed and good to be merged!

**Comment by JxhnnyUt8h** [comment]
> Let me know when this is peer reviewed and good to be merged!

@ericaxu 
Initial contributor did not respond. 
So this pull request can be canceled because of #713 (it includes part of changes that are not in dispute).

**Comment by ericaxu** [comment]
> > Let me know when this is peer reviewed and good to be merged!
> 
> @ericaxu Initial contributor did not respond. So this pull request can be canceled because of #713 (it includes part of changes that are not in dispute).

Thanks, sounds good!

If there's any need you can @ me to re-open it.

**Pull request closed without merging**
