### PR TITLE
Update zh.json

### PR DESCRIPTION
**Pull request by coxde**

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for the pull request!

I don't think "Front-matter" should be translated though, after a quick search. Please see this page: https://wiki.jikexueyuan.com/project/hexo-document/front-matter.html

Let me know what you think.

**Comment by coxde** [comment]
It's true that "扉页" is the result of a literal translation, but there doesn't seem to be a common Chinese translation for "Front-matter" in YAML. Perhaps the traditional Chinese translation could be used - "正文前页"? Or anyone has a better idea?

**Comment by ericaxu** [comment]
My take is that some technical words and phrases can be left as is, since there isn't an official translation for it yet. For example, the word "Markdown".

What do you think?

**Comment by coxde** [comment]
I agree with you! So maybe you could close this pull request and I will submit a new one?

**Pull request closed without merging**
