### PR TITLE
de: second chance for the request 

### PR DESCRIPTION
**Pull request by 42sol-eu**
see https://github.com/42sol-eu/obsidian_translation_shared for discussions and a growing German termbase

### CODE REVIEW

**Comment by 42sol-eu** [comment]
see also https://github.com/obsidianmd/obsidian-translations/pull/567

**Review by Esshahn — CHANGES_REQUESTED** [review]
pls remove "zu" in "Bitte gib den Befehl ein, um den Vim-Modus zu einzuschalten"

**Comment by 42sol-eu** [comment]
hi @ericaxu the German translation is sadly not very well - though I am thankful for all helpers and contributors.

There are many things that have to be changed. But as I gathered up strength and people the documentation/help repository was closed for restructuring and this is still the case since Nov last year. 

Do you see any timeframe when the docs will be finished for translation?

**Comment by 42sol-eu** [comment]
yes

**Comment by ericaxu** [comment]
I see what you mean. Do you want to close this PR or change it to draft in the meantime? I fear that it will get more and more outdated and harder to merge as time goes on.

**Pull request closed without merging**
