### PR TITLE
Initial work on el.json

### PR DESCRIPTION
**Pull request by gtsiam**
I'm creating this PR to avoid any work duplication (however unlikely). I'm still working on this, so it would probably be best to merge when I'm done.

Also, the native language name should be capitalized: `Ελληνικά`, vs the current `ελληνικά`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for pointing that out! Fixed in https://github.com/obsidianmd/obsidian-translations/commit/35020e75752592577f22abf2f5cff7dc3e389348.

**Comment by ericaxu** [comment]
@gtsiam been a long time, do you want us to merge this?

**Comment by gtsiam** [comment]
Yeah, you're right. This has been on my back-burner for way too long; Merge it, once I deal with the conflicts, and maybe I'll come back when/if I have the time. Coming into it, I thought it would be a lot less strings than it was.

**Comment by gtsiam** [comment]
Actually I'm sorry, but no.

There are far too many conflicts, and I'd have to go through each and every translation to make sure it's correct, because most of them were updated at one point or another - That'd take way too many hours, which I am not willing to put in.

If you want to make it easier for translators, I'd recommend using a platform, or maybe po files. json is a pain to deal with, especially when this situation arises. It's not what it was designed for.

I did the majority of the work in translating godot using weblate, and that was very smooth in comparison, I'd recommend it.

**Pull request closed without merging**
