### PR TITLE
Update pl.json

### PR DESCRIPTION
**Pull request by Hitchhiker90**
Added some translations (starting from the bottom).

Also left some comments in the file regarding plural forms for "nouns" - most nouns have two different plural forms in Polish, depending on the number, e.g. for 'words':

2, 3, 4 słowa
5 - 21 słów
22-24 słowa
25-31 słów
etc.

This repeats for all larger numbers. I changed the format to be "words: n" instead of "n words", as in that format there's no expectation of the grammatical form matching the count. I think that is easier than having to modify the code to accommodate this funny feature. ;) And getting it wrong in the original format would look rather awkward.

Btw. is there any expected date by which you're hoping to have the translations completed (e.g. launch date or something)?

### CODE REVIEW

**Comment by ericaxu** [comment]
Re: multiple plural forms: I think I heard that about some other languages. Will look into what we can do about it and update the template strings.

Re: launch date: there's no launch date, don't worry! If a language isn't completed, we will mark it as "partial support" and fall back to English if the translation for a certain piece of text, so it's still better than a fully English interface.

Let me know if that sounds good, if so I'll merge it. If you prefer to work on it some more, we can wait until it's completed.

**Comment by Hitchhiker90** [comment]
Re 1: sure, if that's something you want to include that's great, although I'm not sure if this works exactly the same in other languages (maybe in other Slavic languages it does, honestly I don't know). I don't think anyone will mind the format 'words: n' either.

Re 2: if there's no rush, I can just work on it until done, but that might take some time unfortunately, unless someone else picks it up as well - I've translated a bunch more today, I reckon it's best to merge it now to avoid conflicts later, as I'm not sure when I can pick it up again (could be in a week or two). I'll make another pull request with the updated version shortly.

**Comment by ericaxu** [comment]
Got it, thank you for your amazing work!

**Comment by ericaxu** [comment]
I just realized that JSON cannot contain comments: https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

Do you mind if I remove your comments? Otherwise the JSON is invalid and the language most likely won't work. It's easy to track back to this PR on GitHub so I hope that won't be a big problem.

**Comment by Hitchhiker90** [comment]
Not a problem at all, sorry about this, did not realise either.

**Pull request merged**
