### PR TITLE
Update vi.json

### PR DESCRIPTION
**Pull request by TaQuangKhoi**
I updated vi.json depend on en.json..
I start translate Obsidian to Vietnamese tomorrow.. I will do it day by day..

### CODE REVIEW

**Comment by ericaxu** [comment]
Thank you for your amazing work!

**Comment by khoingm** [comment]
Hello @ericaxu and @TaQuangKhoi,

I'm starting out on GitHub but I'm going to read the manual and guide to contribute in translating Obsidian to Vietnamese in my spare time. 

Hopefully we would be able to introduce Obsidian to more Vietnamese users.

I'm grateful for the invention of the application and it did help me tremendously in my thought capture and process.

Looking forward to be a part of this translating project.

P/S: My name is also Khôi lol 😎

**Comment by TaQuangKhoi** [comment]
Do you know any Vietnamese use Obsidian? 
I know a teacher name **quang**..

**Comment by pantasio** [comment]
hope you guys have a document to make this project going faster.

**Pull request merged**
