### PR TITLE
l10n: zh_TW: full reviewed and translated to 0.13.6

### PR DESCRIPTION
**Pull request by pan93412**
# Notable Changes

## Punctuations

Follow a common typesetting and punctuations standard that brings a better reading experience. It is largely based on the standard from Apple's and [edu.tw](www.edu.tw).

* All the `""` are changed to `「」`
* All the `: ` are changed to `：`
* All the `...` are changed to `……` or `…` (button / next screen)

## Terms

I changed some terminologies to the native one in Chinese (Taiwan) with [繁化姬](https://zhconvert.org), my 2yr+ experience, and the original translators' habit. The reference terminologies are from Microsoft, Apple, and our glossary that has been widely used in open-source applications like OBS Studio and GNOME.

* Some terms are changed to the localized one
  * based on Microsoft and Apple's localization
* Unify the terms 
* Localized some words with <https://zhconvert.org>.
* (#571) `連結` -> `鏈接`
* (#571) `(註冊碼|授權)` -> `憑證`

## Readability

I reordered the order in some sentences to improve their readability.

* Reorder the order in some sentences
* Unify the space between Chinese and English characters.

## Translation

* Translated all the strings to 0.13.6

For collaborators to merge: better to _squash_ this pull request.

### CODE REVIEW

**Comment by ericaxu** [comment]
Wow this is a big refactor! If any maintainer of `zh_TW` can do a review that would be great!

**Comment by pan93412** [comment]
r? (2) @emisjerry
Thanks!

**Comment by emisjerry** [comment]
It looks awesome.

**Review by emisjerry — APPROVED** [review]
Looks good.

**Review by emisjerry — APPROVED** [review]
Looks good.

**Comment by pan93412** [comment]
@emisjerry thanks!
@ericaxu could you help me squash and merge it? thanks :D

**Comment by ericaxu** [comment]
Great, thank you!

**Pull request merged**
