### PR TITLE
Update ru translate

### PR DESCRIPTION
**Pull request by AVAtarMod**
I think "Встроенные плагины" more accurate than "Основные плагины"
Changes should be reviewed as I neither have Obsidian Publish nor Obsidian Sync enabled and thus am missing context for some translations (as and DE pull request author, because he not have that services too)

### CODE REVIEW

**Comment by ericaxu** [comment]
@AVAtarMod do you want to find someone to review it? If you're on Discord, the Russian channel might help.

**Comment by AVAtarMod** [comment]
@ericaxu Thanks, I'll go to channel which you described.

**Review by lisachev — CHANGES_REQUESTED** [review]
Thank you for helping the community. You are welcome to discuss the translation on the Telegram channel. The link is in the ru.termbase file. If you are not on the telegram platform, please let me know and I will review the whole submission here. 
There are some nuances. For example plurals dont work like you expect them to. For Russian we are forced to use : as a workaround. Look at other translations of plurals. 
Core plugins are not embedded. They are still plugins, they just come with the application itself. I would not change the naming. But again - you are welcome to discuss it with other translators in telegram if you like to.

**Comment by AVAtarMod** [comment]
Thank you for help and review my PR, I did little fixes of the translate.

**Review by JxhnnyUt8h — APPROVED** [review]
@ericaxu can be merged from now 😎

**Comment by ericaxu** [comment]
Thank you so much! <3

**Pull request merged**
