### PR TITLE
update ko.json

### PR DESCRIPTION
**Pull request by eric-hansen**

### CODE REVIEW

**Comment by ericaxu** [comment]
Thank you for your amazing work!

Do you want me to merge it now? Or would you like some feedback from a native speaker like discussed on the Discord?

**Comment by ericaxu** [comment]
Also I'm a little concerned that this will cause merge conflicts with the other Korean PR: https://github.com/obsidianmd/obsidian-translations/pull/54

**Comment by eric-hansen** [comment]
If you feel that #54 is better suited for merging then this can be closed and you can merge that one in instead.  There may be conflicts, I was curious about that myself but as that is far more translated than this I wasn't sure if you were wanting this still open or not.

But, if you want to keep this open then feedback would be good, even though I just changed some simple text I know the desire you guys have for the translations.

**Comment by ericaxu** [comment]
I merged #54, not sure if you want to resolve the conflicts so I can merge, or would you rather closing this?

**Comment by eric-hansen** [comment]
No problem, I resolved the conflicts.

**Comment by ericaxu** [comment]
@eric-hansen Thank you! ❤️

**Pull request merged**
