### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by lisachev**
Added some more in-between section translations

### CODE REVIEW

**Comment by VKondakoff** [comment]
@lisachev @ericaxu Sorry to say, but here are some not well-thought translations. Example:

`"drag-to-rearrange": "Перетягивай и расставляй"`
``` "label-previous": "Пред",
 			"label-next": "След",
 			"label-all": "Вс",
```
Please, be more careful the next time! And, as far as I see all of these strings were already translated...

**Comment by lisachev** [comment]
> @lisachev @ericaxu Sorry to say, but here are some not well-thought translations. Example:
> 
> `"drag-to-rearrange": "Перетягивай и расставляй"`
> 
> ```
>  			"label-next": "След",
>  			"label-all": "Вс",
> ```
> 
> Please, be more careful the next time! And, as far as I see all of these strings were already translated...

Sure. I've forked an hour ago or so. With such intense translation I believe my involvement will not be needed at all. 
Happy to see you guys jump into this with such dedication. I will stand by then to support discussions where there will be different ways to say the same in UI

**Comment by VKondakoff** [comment]
👍

**Comment by ericaxu** [comment]
@VKondakoff @lisachev I'll close this then, thank you! It's amazing to see such enthusiasm in translating Obsidian to so many langauges!

**Pull request closed without merging**
