### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by varamsky**
Marked Sanskrit as completed

### CODE REVIEW

**Comment by varamsky** [comment]
Please, let me know when this change can be applied to the new release of Obsidian.

Do these language updates automatically get introduced without a new release or will it be included in the next release?

Anyways could you please be kind enough to let me know when these changes will be reflected in the app.

**Comment by joethei** [comment]
According to my calculation the Sanskrit translation is only 56% complete.
We consider translations to be complete once they are closer to 90%.

**Comment by varamsky** [comment]
Thank you for the response.

@joethei  Could you please share how you get the percentage so that I can check it myself before I raise another request.

I couldn't find the translations for a lot of computer terms that is why they are incomplete.
Some other translations like Farsi(fa.json) were also incomplete that is why I thought that the sanskrit translation in the current form might be accepted.

Anyways, I'll try to bring it as closer to perfection as possible and then raise a request again.
Thank you :)

**Comment by joethei** [comment]
The calculation is done by comparing the translation file with the english version.

**Pull request closed without merging**
