### PR TITLE
Portuguese translation completed!

### PR DESCRIPTION
**Pull request by marcelobrito03**
Portuguese translation completed! now it remains only to update strings if the community deems it necessary.

### CODE REVIEW

**Comment by marcelobrito03** [comment]
I understand that the merge conflicts are unpleasant, however they limit to corrected spelling errors and some changes that IMHO, aim at a better understanding for native Portuguese speakers.

**Comment by DavidsonTwo** [comment]
Nice changes. I'm a brazilian and I'd like to discuss with you some rephrasing updates later

**Comment by ericaxu** [comment]
Thanks for your amazing work, @marcelobrito03 !

Not sure what we should with the conflicted lines, any suggestions?

**Comment by marcelobrito03** [comment]
> Boas mudanças. Sou brasileiro e gostaria de discutir com vocês algumas atualizações de reformulação mais tarde

**Comment by marcelobrito03** [comment]
> Nice changes. I'm a brazilian and I'd like to discuss with you some rephrasing updates later

Thank you very much @DavidsonTwo, it would be great to discuss. I have doubts about the best translation for some situations.

**Comment by DavidsonTwo** [comment]
My Discord is DavidsonTwo#7272. We can discuss it bether there

**Comment by ericaxu** [comment]
There's a #translation Discord channel if you guys aren't aware already. Looking forward to an amazing translation!

**Comment by marcelobrito03** [comment]
> Thanks for your amazing work, @marcelobrito03 !
> 
> Not sure what we should with the conflicted lines, any suggestions?

You're welcome @ericaxu, thanks for creating an Obsidian, it's a pleasure to help with something so good.  😀

As for the conflict lines, as @DavidsonTwo is the author of some lines where there was conflict and how he approved the changes I made, so my suggestion is to merge my pull request. That way, in the future we can make another pull request with only small fine adjustments.

**Comment by marcelobrito03** [comment]
> My Discord is DavidsonTwo#7272. We can discuss it bether there
> There's a #translation Discord channel if you guys aren't aware already. Looking forward to an amazing translation!

Ok @ericaxu. For convenience, me and @DavidsonTwo have already discussed in particular some improvements to this pull request, should it be accepted. If necessary, for further improvements, we will use the #translation discord channel.

**Comment by hellenx34** [comment]
Great job! @marcelobrito03
I'm from Brazil too.

**Comment by marcelobrito03** [comment]
I will close this pull request and make an update based on a new branch.

**Pull request closed without merging**
