### PR TITLE
de: translated new strings for 0.12.1.; en: fixed possible typo

### PR DESCRIPTION
**Pull request by 7aqdxe6f**
Hi there!

I am not quite sure about some of the translations (I am still using v0.11.13 and thus am missing context for some of the settings), maybe other translators could weigh in on this (especially for the translations of lines 274–278 & 596–600)?

For example I think a better translation for "match" in section search (from line 578 onward) might help. Cannot say this for certain though, as I could not find the German translations in Obsidian v0.11.13. For now I translated using the German terms that were already in use.

Also found a possible mistake in en.json.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi thanks! Do you want to wait until 0.12.1 is released to public to double check or merge it as soon as possible?

(We can always fix the translation later if something goes wrong.)

**Comment by 7aqdxe6f** [comment]
I think it would be better to wait for the release and/or a review from other translators to assure the accuracy of the translations.

**Comment by ericaxu** [comment]
Got it! Let me know when it's ready to be merged.

**Comment by 7aqdxe6f** [comment]
Will do, thank you.

**Comment by FloriF** [comment]
@7aqdxe6f
- I think since your translations are similar to what has already been translated for the same section (lines 578ff), so I think that's fine.
- The only thing I think should be changed is the keyboard shortcut on line 109. I assume that german users would be more familiar with STRG instead of CTRL. 
- Also, thanks for correcting the typos and making the tranlsations more uniform (verb at the end of the sentence)!

**Comment by 7aqdxe6f** [comment]
Thanks for pointing that out @FloriF!

**Comment by 7aqdxe6f** [comment]
@ericaxu PR should be ready to merge now, the translation of the new strings should match the style of the previous translations.

**Comment by ericaxu** [comment]
Thank you for your work! <3

**Pull request merged**
