### PR TITLE
Update zh.json

### PR DESCRIPTION
**Pull request by x-Ai**
更新部分中文翻译，但是需要开发人员调整部分代码才会生效

```
-------------------------------------------------------
1: Translation of "New Tab" in the main interface

app.js

t.prototype.getDisplayText=function(){return"New tab"}

t.prototype.getDisplayText = function() {
    return yf.interface.labelNewTab() || "New tab";
}

-------------------------------------------------------
2: Bookmarking Translations

i18n.js

"plugins": {
    "name": "Plugins", 
    "bookmarks": {
        "menuOptBookmarkBlock": "Bookmark this block...", 
        "labelEditBookmark": "Edit bookmark",
        "labelAddBookmark": "Add bookmark"
    }
}

app.js

var a = i ? "Edit bookmark" : "Add bookmark";
var a=i?gK.labelEditBookmark():gK.labelAddBookmark();


zh.json

"plugins": {
    "name": "Plugins", 
    "bookmarks": {
        "menu-opt-bookmark-block": "收藏此区块...", 
        "label-edit-bookmark": "编辑书签",
        "label-add-bookmark": "添加书签"
    }
}

-------------------------------------------------------
3：Hokeys Translation

app.js

name: "Go to last tab",
name: tf.commands.goToLastTab(),

name: "Go to tab #".concat(e),
name: tf.commands.goToTab().concat(e),

name: "Go to next tab",
name: tf.commands.goToNextTab(),

name: "Go to previous tab",
name: tf.commands.goToPreviousTab(),

t.addCommand({id:"app:show-release-notes",name: "Show Release Notes"
t.addCommand({id:"app:show-release-notes",name: tf.commands.showReleaseNotes()


i18n.js

"commands": {
    "showReleaseNotes": "Show Release Notes",
    "goToLastTab": "Go to last tab",
    "goToTab": "Go to tab #",
    "goToNextTab": "Go to next tab",
    "goToPreviousTab": "Go to previous tab"
}

zh.json

"commands": {
    "show-release-notes": "显示更新说明",
    "go-to-last-tab": "转到最后一个标签页",
    "go-to-tab": "转到标签页 #",
    "go-to-next-tab": "转到下一个标签页",
    "go-to-previous-tab": "转到上一个标签页"
}
```

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi, thanks for the suggestions! I've patched the code and the strings will be ready in the next release of translation plugins. I'll leave this issue open until the translations are added to `zh.json`.

**Comment by x-Ai** [comment]
> Hi, thanks for the suggestions! I've patched the code and the strings will be ready in the next release of translation plugins. I'll leave this issue open until the translations are added to `zh.json`.

no problem, after this translation is merged, there are very few strings left that haven't been localized. The remaining ones should be the issues with the software interface menu mentioned in issues/808.

**Comment by ericaxu** [comment]
Just had a release, do you see these as fixed? 😊

**Comment by x-Ai** [comment]
> Just had a release, do you see these as fixed? 😊

I have already done the check in version 1.4.5, all the problems have been fixed, well done.😆

**Comment by ericaxu** [comment]
Looks like the translations have been added as well. Should we close this PR?

**Pull request closed without merging**
