### PR TITLE
Update el.json

### PR DESCRIPTION
**Pull request by B0ras**

### CODE REVIEW

**Comment by ericaxu** [comment]
Looks like you're editing all the whitespace, could you take a look at that? Thanks!

**Comment by ericaxu** [comment]
@B0ras Hi! Did you get a chance to take a look at my previous comment?

**Comment by B0ras** [comment]
Terribly sorry, I have a lot on my plate right now but I am trying to fix it as fast as I can.

**Comment by ericaxu** [comment]
> Terribly sorry, I have a lot on my plate right now but I am trying to fix it as fast as I can.

No worries, just want to make sure you saw it. No hurry to fix it.

**Pull request closed without merging**
