### PR TITLE
Another update to the spanish translation

### PR DESCRIPTION
**Pull request by argenos**
There are some lines that were translated differently in #68.

### CODE REVIEW

**Comment by ericaxu** [comment]
Thank you for your amazing work!

Should I merge #68 (after it's resolved) before this one? Not sure about the dependencies between them.

**Comment by argenos** [comment]
Let's wait to hear back from @Yellsin, I can merge his branch onto mine depending on what we agree. We can close #68 and merge this one with both our changes. (Of course, if @Yellsin is ok with that as well).

**Comment by Yellsin** [comment]
Thank you @argenos, I agree with your changes.

**Comment by argenos** [comment]
@Yellsin should we merge this instead of #68?

**Comment by Yellsin** [comment]
Yes @argenos, I think we should merge this one instead of #68

**Comment by argenos** [comment]
@ericaxu LGTM!

**Comment by ericaxu** [comment]
Thank you guys! ❤️

**Pull request merged**
