### PR TITLE
UK Update nouns, editor and interface translation

### PR DESCRIPTION
**Pull request by BroMandarin**

### CODE REVIEW

**Comment by BroMandarin** [comment]
More changes to come. Don't merge for now.

**Comment by BroMandarin** [comment]
I would like clarification regarding interface.label-enter-to-create (Enter to create). Does this imply Enter key?

**Comment by BroMandarin** [comment]
I think it's sufficient to merge. Don't want to make too many changes at once.

**Comment by ericaxu** [comment]
Thank you for your work!

**Pull request merged**
