### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by k-andzhanovskii**
Appearance, hotkeys, about, account, editor, spellcheck, command-palette, markdown-format-importer, daily-notes, zettelkasten-prefixer, outline and slides are finished.

### CODE REVIEW

**Comment by ericaxu** [comment]
Sorry I think there are some conflicts. Could you take a look and see if it's possible to resolve them please?

**Comment by VKondakoff** [comment]
@k-andzhanovskii: I suggest to translate Vault as Хранилище and not Сейф. Do you agree?

**Comment by k-andzhanovskii** [comment]
> @k-andzhanovskii: I suggest to translate Vault as Хранилище and not Сейф. Do you agree?

I think I do. 'Хранилище' was the first translation that came to my mind, but 'Сейф' is much shorter and the icon in the app is literally a 'сейф'. At the same time I think 'сейф' has more mental association with money and similar valuables in the Russian language. Let's go with 'Хранилище'. I will fix it in my translation.

I am going to fix the rest of the conflicts in my current pull request, but would like to discuss some of the them if you don't mind.

Should we split the rest of translation between two of as (as soon as there are no more contributors right now), so we can avoid conflicts in pull requests in the future?

**Comment by VKondakoff** [comment]
Great, looks I already translated all occurrences of 'Vault' in the file. Do you use Telegram? Ping @Valery_Kondakoff.

**Pull request closed without merging**
