### PR TITLE
Added more translations to hindi language

### PR DESCRIPTION
**Pull request by ashwinjadhav818**
Updated a bunch of translation to the settings section.

### CODE REVIEW

**Comment by ericaxu** [comment]
Unfortunately there are some conflicts as I merged a Hindi translation PR a bit earlier. Can you see if you can resolve them?

**Comment by ericaxu** [comment]
Hi @ashwinjadhav818 , did you see my message above?

**Comment by ashwinjadhav818** [comment]
Oh yes sorry I forgot to reply, will update that.

**Comment by joethei** [comment]
Hi @ashwinjadhav818 do you intend to fix the merge conflict?

**Comment by ashwinjadhav818** [comment]
I have resolved the conflict.

**Comment by ashwinjadhav818** [comment]
@joethei I did resolve the conflict, the pr is ready to merge.

**Comment by joethei** [comment]
Now I don't see any translation changes, only a deletion of the last empty line.

**Comment by joethei** [comment]
Closing as this PR has gone stale.
If you are ready continue feel free to reopen it.

**Pull request closed without merging**
