### PR TITLE
Typo on pt-BR native language name

### PR DESCRIPTION
**Pull request by nighto**
Does the list here populate the languages list on app? Just noticed the typo there, and also here.

### CODE REVIEW

**Comment by nighto** [comment]
image

This dropdown list, I mean.

**Comment by liamcain** [comment]
That list is currently internal only, but I can change it. What is the typo? Should it be `Português do Brasil`?

**Comment by nighto** [comment]
Yes @liamcain

**Comment by joethei** [comment]
Update is released

**Pull request closed without merging**
