### PR TITLE
Add: Amharic language

### PR DESCRIPTION
**Pull request by letter-Seid**
Amharic the language of my Country Ethiopia.

### CODE REVIEW

**Comment by letter-Seid** [comment]
For reference: 
ISO 639-1 | [am](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=am)
https://en.wikipedia.org/wiki/Amharic

**Comment by ericaxu** [comment]
> For reference: ISO 639-1 | [am](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=am) https://en.wikipedia.org/wiki/Amharic

Thanks!

Could you update the README to add Amharic too please?

**Comment by letter-Seid** [comment]
updated the README to include the language and the order of languages based on their name it was messed up in my opinion.

**Comment by ericaxu** [comment]
> updated the README to include the language and the order of languages based on their name it was messed up in my opinion.

Thanks for helping! We were ordering the languages by their code, alphabetically. I think keeping it as is is fine, thanks!

**Comment by letter-Seid** [comment]
> > updated the README to include the language and the order of languages based on their name it was messed up in my opinion.
> 
> Thanks for helping! We were ordering the languages by their code, alphabetically. I think keeping it as is is fine, thanks!

fixed the order; I don't know which language code standard you are using but it doesn't look ordered that way. I think you should look into that. or maybe I could order them in `ISO 639`. And thanks for everything. In my opinion you are changing the world. The app is just as great but the features and concepts are out of this world 🙏

**Comment by letter-Seid** [comment]
@ericaxu Amharic `am` is completed as far as I checked.
If the file name [am.json](https://github.com/letter-Seid/obsidian-translations/blob/master/am.json) gives you a problem I can change it.
I hope that I see it in the next release
Thanks

**Comment by ericaxu** [comment]
@letter-Seid Thank you so much for your hard work!

Is `am.json` translated from the latest `en.json` file?

**Comment by letter-Seid** [comment]
> @letter-Seid Thank you so much for your hard work!
> 
> Is `am.json` translated from the latest `en.json` file?

Yes it is updated and translated to version 1.1.6.

**Pull request merged**
